name: Build NPM
description: Builds the project for NPM release.

inputs:
  scope:
    description: Scope
    required: true
  registry-url:
    description: Registry URL
    required: false
  version:
    description: Version
    required: false
    default: 0.0.0-test
  dist:
    description: The artifact name for the build output.
    required: false
    default: dist-npm

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: ${{ inputs.registry-url }}

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Install
      shell: bash
      run: make install

    - name: Build
      shell: bash
      run: deno task build-npm ${{ inputs.version }} ${{ inputs.scope }}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.dist }}
        path: dist
