name: Build NPM
description: Builds the project for NPM release.

inputs:
  scope:
    description: Scope
    required: true
  registry-url:
    description: Registry URL
    required: false
  version:
    description: Version
    required: false
    default: 0.0.0-test
  dist:
    description: The artifact name for the build output.
    required: false
    default: dist-npm
  test:
    description: Run tests after building for NPM.
    required: false
    default: "true"
  node-version:
    description: NodeJS version
    required: false
    default: "latest"
  compile-target:
    description: Compilation Target
    required: false
    default: Latest

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Build
      shell: bash
      run: deno task build-npm ${{ inputs.version }} ${{ inputs.scope }} ${{ fromJSON(inputs.test) && '--test' || '--no-test' }} --compile-target=${{ inputs.compile-target }}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.dist }}
        path: dist/npm
